; Listing generated by Microsoft (R) Optimizing Compiler Version 19.14.26428.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\ghdms\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cpp"
